<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ArticleSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::statement("INSERT INTO public.articles(name, photos, description, created_at, updated_at) VALUES ('CUÑETE DE PINTURA PARA EXTERIORES BLANCO TRÁFICO.', ARRAY['abc'], 'PINTURAS / EXTERIORES, BLANCO TRÁFICO, CUÑETE(S) DE 18.92 Litro(s), Cantidad: 1', now(), now())");
        DB::statement("INSERT INTO public.articles(name, photos, description, created_at, updated_at) VALUES ('GALÓN DE PINTURA PARA EXTERIORES BLANCO TRÁFICO.', ARRAY['abc'], 'PINTURAS / EXTERIORES, BLANCO TRÁFICO, GALÓN(ES) DE 3.78 Litro(s), Cantidad: 1', now(), now())");
        DB::statement("INSERT INTO public.articles(name, photos, description, created_at, updated_at) VALUES ('MEDIO GALÓN DE PINTURA PARA EXTERIORES BLANCO TRÁFICO.', ARRAY['abc'], 'PINTURAS / EXTERIORES, BLANCO TRÁFICO, GALÓN(ES) DE 1.89 Litro(s), Cantidad: 1', now(), now())");
        DB::statement("INSERT INTO public.articles(name, photos, description, created_at, updated_at) VALUES ('CUARTO DE GALÓN DE PINTURA PARA EXTERIORE BLANCO TRÁFICO.', ARRAY['abc'], 'PINTURAS / EXTERIORES, BLANCO TRÁFICO, GALÓN(ES) DE 0.94 Litro(s), Cantidad: 1', now(), now())");
        DB::statement("INSERT INTO public.articles(name, photos, description, created_at, updated_at) VALUES ('CUÑETE DE PINTURA PA EXTERIORES BLANCO TRÁFICO MONTANA.', ARRAY['abc'], 'PINTURAS / EXTERIORES, BLANCO TRÁFICO, MONTANA, CUÑETE(S) DE 18.92 Litro(s), Cantidad: 1', now(), now())");
        DB::statement("INSERT INTO public.articles(name, photos, description, created_at, updated_at) VALUES ('GALÓN DE PINTURA PARA EXTERIORES BLANCO TRÁFICO MONTANA.', ARRAY['abc'], 'PINTURAS / EXTERIORES, BLANCO TRÁFICO, MONTANA, GALÓN(ES) DE 3.78 Litro(s), Cantidad: 1', now(), now())");
        DB::statement("INSERT INTO public.articles(name, photos, description, created_at, updated_at) VALUES ('MEDIO GALÓN DE PINTURA PARA EXTERIORES BLANCO TRÁFICO MONTANA.', ARRAY['abc'], 'PINTURAS / EXTERIORES, BLANCO TRÁFICO, MONTANA, GALÓN(ES) DE 1.89 Litro(s), Cantidad: 1', now(), now())");
        DB::statement("INSERT INTO public.articles(name, photos, description, created_at, updated_at) VALUES ('CUARTO DE GALÓN PINTURA PARA EXTERIORES BLANCO TRÁFICO MONTANA.', ARRAY['abc'], 'PINTURAS / EXTERIORES, BLANCO TRÁFICO, MONTANA, GALÓN(ES) DE 0.94 Litro(s), Cantidad: 1', now(), now())");
        DB::statement("INSERT INTO public.articles(name, photos, description, created_at, updated_at) VALUES ('CUÑETE DE PINTURA PARA  EXTERIORES BLANCO TRÁFICO MANPICA.', ARRAY['abc'], 'PINTURAS / EXTERIORES, BLANCO TRÁFICO, MANPICA, CUÑETE(S) DE 18.92 Litro(s), Cantidad: 1', now(), now())");
        DB::statement("INSERT INTO public.articles(name, photos, description, created_at, updated_at) VALUES ('GALÓN DE PINTURA PARA EXTERIORES BLANCO TRÁFICO MANPICA.', ARRAY['abc'], 'PINTURAS / EXTERIORES, BLANCO TRÁFICO, MANPICA, GALÓN(ES) DE 3.78 Litro(s), Cantidad: 1', now(), now())");
        DB::statement("INSERT INTO public.articles(name, photos, description, created_at, updated_at) VALUES ('MEDIO GALÓN PINTURA PARA EXTERIORES BLANCO TRÁFICO MANPICA.', ARRAY['abc'], 'PINTURAS / EXTERIORES, BLANCO TRÁFICO, MANPICA, GALÓN(ES) DE 1.89 Litro(s), Cantidad: 1', now(), now())");
        DB::statement("INSERT INTO public.articles(name, photos, description, created_at, updated_at) VALUES ('CUARTO DE GALÓN DE PINTURA PARA EXTERIORES BLANCO TRÁFICO MANPICA.', ARRAY['abc'], 'PINTURAS / EXTERIORES, BLANCO TRÁFICO, MANPICA, GALÓN(ES) DE 0.94 Litro(s), Cantidad: 1', now(), now())");
        DB::statement("INSERT INTO public.articles(name, photos, description, created_at, updated_at) VALUES ('CUÑETE DE PINTURA PARA INTERIORES BLANCO OSTRA.', ARRAY['abc'], 'PINTURAS / INTERIORES, BLANCO OSTRA, CUÑETE(S) DE 18.92 Litro(s), Cantidad: 1', now(), now())");
        DB::statement("INSERT INTO public.articles(name, photos, description, created_at, updated_at) VALUES ('GALÓN DE PINTURA PARA INTERIORES BLANCO OSTRA.', ARRAY['abc'], 'PINTURAS / INTERIORES, BLANCO OSTRA, GALÓN(ES) DE 3.78 Litro(s), Cantidad: 1', now(), now())");
        DB::statement("INSERT INTO public.articles(name, photos, description, created_at, updated_at) VALUES ('GALÓN DE PINTURA PARA INTERIORES BLANCO OSTRA.', ARRAY['abc'], 'PINTURAS / INTERIORES, BLANCO OSTRA, GALÓN(ES) DE 1.89 Litro(s), Cantidad: 1', now(), now())");
        DB::statement("INSERT INTO public.articles(name, photos, description, created_at, updated_at) VALUES ('CUARTO DE GALÓN PINTURAS PARA INTERIORES BLANCO OSTRA.', ARRAY['abc'], 'PINTURAS / INTERIORES, BLANCO OSTRA, GALÓN(ES) DE 0.94 Litro(s), Cantidad: 1', now(), now())");
        DB::statement("INSERT INTO public.articles(name, photos, description, created_at, updated_at) VALUES ('CUÑETE DE PINTURA PARA INTERIORES BLANCO OSTRA MONTANA.', ARRAY['abc'], 'PINTURAS / INTERIORES, BLANCO OSTRA, MONTANA, CUÑETE(S) DE 18.92 Litro(s), Cantidad: 1', now(), now())");
        DB::statement("INSERT INTO public.articles(name, photos, description, created_at, updated_at) VALUES ('GALÓN DE PINTURA PARA INTERIORES BLANCO OSTRA MONTANA.', ARRAY['abc'], 'PINTURAS / INTERIORES, BLANCO OSTRA, MONTANA, GALÓN(ES) DE 3.78 Litro(s), Cantidad: 1', now(), now())");
        DB::statement("INSERT INTO public.articles(name, photos, description, created_at, updated_at) VALUES ('MEDIO GALÓN PINTURA PARA INTERIORES BLANCO OSTRA MONTANA.', ARRAY['abc'], 'PINTURAS / INTERIORES, BLANCO OSTRA, MONTANA, GALÓN(ES) DE 1.89 Litro(s), Cantidad: 1', now(), now())");
        DB::statement("INSERT INTO public.articles(name, photos, description, created_at, updated_at) VALUES ('GALÓN DE PINTURA PARA INTERIORES BLANCO OSTRA MONTANA.', ARRAY['abc'], 'PINTURAS / INTERIORES, BLANCO OSTRA, MONTANA, GALÓN(ES) DE 0.94 Litro(s), Cantidad: 1', now(), now())");
        DB::statement("INSERT INTO public.articles(name, photos, description, created_at, updated_at) VALUES ('CUÑETE DE PINTURA PARA INTERIORES BLANCO OSTRA MANPICA.', ARRAY['abc'], 'PINTURAS / INTERIORES, BLANCO OSTRA, MANPICA, CUÑETE(S) DE 18.92 Litro(s), Cantidad: 1', now(), now())");
        DB::statement("INSERT INTO public.articles(name, photos, description, created_at, updated_at) VALUES ('GALÓN DE PINTURA PARA INTERIORES BLANCO OSTRA MANPICA.', ARRAY['abc'], 'PINTURAS / INTERIORES, BLANCO OSTRA, MANPICA, GALÓN(ES) DE 3.78 Litro(s), Cantidad: 1', now(), now())");
        DB::statement("INSERT INTO public.articles(name, photos, description, created_at, updated_at) VALUES ('MEDIO GALÓN DE PINTURA PARA INTERIORES, BLANCO OSTRA MANPICA.', ARRAY['abc'], 'PINTURAS / INTERIORES, BLANCO OSTRA, MANPICA, GALÓN(ES) DE 1.89 Litro(s), Cantidad: 1', now(), now())");
        DB::statement("INSERT INTO public.articles(name, photos, description, created_at, updated_at) VALUES ('CUARTO DE GALÓN DE PINTURA PARA INTERIORES BLANCO OSTRA MANPICA.', ARRAY['abc'], 'PINTURAS / INTERIORES, BLANCO OSTRA, MANPICA, GALÓN(ES) DE 0.94 Litro(s), Cantidad: 1', now(), now())");
        DB::statement("INSERT INTO public.articles(name, photos, description, created_at, updated_at) VALUES ('CUÑETE DE SELLADOR GRIS.', ARRAY['abc'], 'PINTURAS / OTROS, SELLADOR GRIS, CUÑETE(S) DE 18.92 Litro(s), Cantidad: 1', now(), now())");
        DB::statement("INSERT INTO public.articles(name, photos, description, created_at, updated_at) VALUES ('GALÓN DE SELLADOR GRIS.', ARRAY['abc'], 'PINTURAS / OTROS, SELLADOR GRIS, GALÓN(ES) DE 3.78 Litro(s), Cantidad: 1', now(), now())");
        DB::statement("INSERT INTO public.articles(name, photos, description, created_at, updated_at) VALUES ('MEDIO GALÓN DE SELLADOR GRIS.', ARRAY['abc'], 'PINTURAS / OTROS, SELLADOR GRIS, GALÓN(ES) DE 1.89 Litro(s), Cantidad: 1', now(), now())");
        DB::statement("INSERT INTO public.articles(name, photos, description, created_at, updated_at) VALUES ('CUARTO DE GALÓN DE SELLADOR GRIS.', ARRAY['abc'], 'PINTURAS / OTROS, SELLADOR GRIS, GALÓN(ES) DE 0.94 Litro(s), Cantidad: 1', now(), now())");
        DB::statement("INSERT INTO public.articles(name, photos, description, created_at, updated_at) VALUES ('CUÑETE DE SELLADOR GRIS MONTANA.', ARRAY['abc'], 'PINTURAS / OTROS, SELLADOR GRIS, MONTANA, CUÑETE(S) DE 18.92 Litro(s), Cantidad: 1', now(), now())");
        DB::statement("INSERT INTO public.articles(name, photos, description, created_at, updated_at) VALUES ('GALÓN DE SELLADOR GRIS MONTANA.', ARRAY['abc'], 'PINTURAS / OTROS, SELLADOR GRIS, MONTANA, GALÓN(ES) DE 3.78 Litro(s), Cantidad: 1', now(), now())");
        DB::statement("INSERT INTO public.articles(name, photos, description, created_at, updated_at) VALUES ('MEDIO GALÓN DE SELLADOR GRIS MONTANA.', ARRAY['abc'], 'PINTURAS / OTROS, SELLADOR GRIS, MONTANA, GALÓN(ES) DE 1.89 Litro(s), Cantidad: 1', now(), now())");
        DB::statement("INSERT INTO public.articles(name, photos, description, created_at, updated_at) VALUES ('CUARTO DE GALÓN DE SELLADOR GRIS MONTANA.', ARRAY['abc'], 'PINTURAS / OTROS, SELLADOR GRIS, MONTANA, GALÓN(ES) DE 0.94 Litro(s), Cantidad: 1', now(), now())");
        DB::statement("INSERT INTO public.articles(name, photos, description, created_at, updated_at) VALUES ('CUÑETE DE SELLADOR GRIS MANPICA.', ARRAY['abc'], 'PINTURAS / OTROS, SELLADOR GRIS, MANPICA, CUÑETE(S) DE 18.92 Litro(s), Cantidad: 1', now(), now())");
        DB::statement("INSERT INTO public.articles(name, photos, description, created_at, updated_at) VALUES ('GALÓN DE SELLADOR GRIS MANPICA.', ARRAY['abc'], 'PINTURAS / OTROS, SELLADOR GRIS, MANPICA, GALÓN(ES) DE 3.78 Litro(s), Cantidad: 1', now(), now())");
        DB::statement("INSERT INTO public.articles(name, photos, description, created_at, updated_at) VALUES ('MEDIO GALÓN DE SELLADOR GRIS MANPICA.', ARRAY['abc'], 'PINTURAS / OTROS, SELLADOR GRIS, MANPICA, GALÓN(ES) DE 1.89 Litro(s), Cantidad: 1', now(), now())");
        DB::statement("INSERT INTO public.articles(name, photos, description, created_at, updated_at) VALUES ('CUARTO DE GALÓN DE SELLADOR GRIS MANPICA.', ARRAY['abc'], 'PINTURAS / OTROS, SELLADOR GRIS, MANPICA, GALÓN(ES) DE 0.94 Litro(s), Cantidad: 1', now(), now())");
        DB::statement("INSERT INTO public.articles(name, photos, description, created_at, updated_at) VALUES ('PAQUETE DE JABON DE BARRA 110 GRAMOS.', ARRAY['abc'], 'PRODUCTOS DE LIMPIEZA / ASEO PERSONAL, JABON DE BARRA, PAQUETE(S) DE 110 Gramo(s), Cantidad: 1', now(), now())");
        DB::statement("INSERT INTO public.articles(name, photos, description, created_at, updated_at) VALUES ('PAQUETE DE JABON DE BARRA PROTEX 110 GRAMOS.', ARRAY['abc'], 'PRODUCTOS DE LIMPIEZA / ASEO PERSONAL, JABON DE BARRA, PROTEX, PAQUETE(S) DE 110 Gramo(s), Cantidad: 1', now(), now())");
        DB::statement("INSERT INTO public.articles(name, photos, description, created_at, updated_at) VALUES ('PAQUETE DE JABON DE BARRA REXONA 110 GRAMOS.', ARRAY['abc'], 'PRODUCTOS DE LIMPIEZA / ASEO PERSONAL, JABON DE BARRA, REXONA, PAQUETE(S) DE 110 Gramo(s), Cantidad: 1', now(), now())");
        DB::statement("INSERT INTO public.articles(name, photos, description, created_at, updated_at) VALUES ('POTE DE DESODORANTE ROLLON 90 MILILITROS.', ARRAY['abc'], 'PRODUCTOS DE LIMPIEZA / ASEO PERSONAL, DESODORANTE ROLLON, POTE(S) DE 90 Mililitro(s), Cantidad: 1', now(), now())");
        DB::statement("INSERT INTO public.articles(name, photos, description, created_at, updated_at) VALUES ('POTE DE DESODORANTE ROLLON REXONA 90 MILILITROS.', ARRAY['abc'], 'PRODUCTOS DE LIMPIEZA / ASEO PERSONAL, DESODORANTE ROLLON, REXONA, POTE(S) DE 90 Mililitro(s), Cantidad: 1', now(), now())");
        DB::statement("INSERT INTO public.articles(name, photos, description, created_at, updated_at) VALUES ('POTE DE  DESODORANTE ROLLON EVERY NIGHT 90 MILILITROS.', ARRAY['abc'], 'PRODUCTOS DE LIMPIEZA / ASEO PERSONAL, DESODORANTE ROLLON, EVERY NIGHT, POTE(S) DE 90 Mililitro(s), Cantidad: 1', now(), now())");
        DB::statement("INSERT INTO public.articles(name, photos, description, created_at, updated_at) VALUES ('POTE DE SHAMPOO 200 MILILITROS.', ARRAY['abc'], 'PRODUCTOS DE LIMPIEZA / ASEO PERSONAL, SHAMPOO, POTE(S) DE 200 Mililitro(s), Cantidad: 1', now(), now())");
        DB::statement("INSERT INTO public.articles(name, photos, description, created_at, updated_at) VALUES ('POTE DE  SHAMPOO EVERY NIGHT 200 MILILITROS.', ARRAY['abc'], 'PRODUCTOS DE LIMPIEZA / ASEO PERSONAL, SHAMPOO, EVERY NIGHT, POTE(S) DE 200 Mililitro(s), Cantidad: 1', now(), now())");
        DB::statement("INSERT INTO public.articles(name, photos, description, created_at, updated_at) VALUES ('POTE DE SHAMPOO PANTENE 200 MILILITROS.', ARRAY['abc'], 'PRODUCTOS DE LIMPIEZA / ASEO PERSONAL, SHAMPOO, PANTENE, POTE(S) DE 200 Mililitro(s), Cantidad: 1', now(), now())");
        DB::statement("INSERT INTO public.articles(name, photos, description, created_at, updated_at) VALUES ('FRASCO DE DETERGENTE LÍQUIDO 1 LITRO.', ARRAY['abc'], 'PRODUCTOS DE LIMPIEZA / HIGIENE DEL HOGAR, DETERGENTE LÍQUIDO, FRASCO(S) DE 1 Litro(s), Cantidad: 1', now(), now())");
        DB::statement("INSERT INTO public.articles(name, photos, description, created_at, updated_at) VALUES ('FRASCO DE DETERGENTE LÍQUIDO LAVANSAN 1 LITRO.', ARRAY['abc'], 'PRODUCTOS DE LIMPIEZA / HIGIENE DEL HOGAR, DETERGENTE LÍQUIDO, LAVANSAN, FRASCO(S) DE 1 Litro(s), Cantidad: 1', now(), now())");
        DB::statement("INSERT INTO public.articles(name, photos, description, created_at, updated_at) VALUES ('FRASCO DE  DETERGENTE LÍQUIDO LAS LLAVES 1 LITRO.', ARRAY['abc'], 'PRODUCTOS DE LIMPIEZA / HIGIENE DEL HOGAR, DETERGENTE LÍQUIDO, LAS LLAVES, FRASCO(S) DE 1 Litro(s), Cantidad: 1', now(), now())");
        DB::statement("INSERT INTO public.articles(name, photos, description, created_at, updated_at) VALUES ('FRASCO DE DESINFECTANTE 1 LITRO.', ARRAY['abc'], 'PRODUCTOS DE LIMPIEZA / HIGIENE DEL HOGAR, DESINFECTANTE, FRASCO(S) DE 1 Litro(s), Cantidad: 1', now(), now())");
        DB::statement("INSERT INTO public.articles(name, photos, description, created_at, updated_at) VALUES ('FRASCO DE DESINFECTANTE LAVANSAN 1 LITRO.', ARRAY['abc'], 'PRODUCTOS DE LIMPIEZA / HIGIENE DEL HOGAR, DESINFECTANTE, LAVANSAN, FRASCO(S) DE 1 Litro(s), Cantidad: 1', now(), now())");
        DB::statement("INSERT INTO public.articles(name, photos, description, created_at, updated_at) VALUES ('FRASCO DE DESINFECTANTE LAS LLAVES 1 LITRO.', ARRAY['abc'], 'PRODUCTOS DE LIMPIEZA / HIGIENE DEL HOGAR, DESINFECTANTE, LAS LLAVES, FRASCO(S) DE 1 Litro(s), Cantidad: 1', now(), now())");
        DB::statement("INSERT INTO public.articles(name, photos, description, created_at, updated_at) VALUES ('ALICATE CHANNELLOCK.', ARRAY['abc'], 'HERRAMIENTAS, ALICATE, CHANNELLOCK, 1 Unidad(es), Cantidad: 1', now(), now())");
        DB::statement("INSERT INTO public.articles(name, photos, description, created_at, updated_at) VALUES ('ALICATE STANLEY.', ARRAY['abc'], 'HERRAMIENTAS, ALICATE, STANLEY, 1 Unidad(es), Cantidad: 1', now(), now())");
        DB::statement("INSERT INTO public.articles(name, photos, description, created_at, updated_at) VALUES ('ALICATE.', ARRAY['abc'], 'HERRAMIENTAS, ALICATE, 1 Unidad(es), Cantidad: 1', now(), now())");
        DB::statement("INSERT INTO public.articles(name, photos, description, created_at, updated_at) VALUES ('DESTORNILLADOR GEDORE.', ARRAY['abc'], 'HERRAMIENTAS, DESTORNILLADOR, GEDORE, 1 Unidad(es), Cantidad: 1', now(), now())");
        DB::statement("INSERT INTO public.articles(name, photos, description, created_at, updated_at) VALUES ('DESTORNILLADOR BOSCH.', ARRAY['abc'], 'HERRAMIENTAS, DESTORNILLADOR, BOSCH, 1 Unidad(es), Cantidad: 1', now(), now())");
        DB::statement("INSERT INTO public.articles(name, photos, description, created_at, updated_at) VALUES ('DESTORNILLADOR.', ARRAY['abc'], 'HERRAMIENTAS, DESTORNILLADOR, 1 Unidad(es), Cantidad: 1', now(), now())");
    }
}
